-- Biblioteca completa de exercícios de musculação, organizada por grupo muscular
-- (equivalente em cobertura ao catálogo de apps como Hevy/Strong, com nomenclatura própria).

CREATE UNIQUE INDEX IF NOT EXISTS idx_exercicios_nome_unique ON exercicios (nome);

-- Normaliza os 10 exercícios de teste já cadastrados para a nova nomenclatura/taxonomia
UPDATE exercicios SET nome = 'Supino Reto (Barra)' WHERE nome = 'Supino Reto';
UPDATE exercicios SET nome = 'Crucifixo Reto (Halteres)' WHERE nome = 'Crucifixo Halteres';
UPDATE exercicios SET nome = 'Agachamento Livre (Barra)', grupo_muscular = 'Quadríceps' WHERE nome = 'Agachamento Livre';
UPDATE exercicios SET grupo_muscular = 'Quadríceps' WHERE nome = 'Leg Press 45°';
UPDATE exercicios SET nome = 'Puxada Frontal (Pegada Aberta)' WHERE nome = 'Puxada Frontal';
UPDATE exercicios SET nome = 'Remada Curvada (Barra)' WHERE nome = 'Remada Curvada';
UPDATE exercicios SET nome = 'Rosca Direta (Barra)' WHERE nome = 'Rosca Direta';
UPDATE exercicios SET nome = 'Tríceps Corda (Polia)' WHERE nome = 'Tríceps Corda';
UPDATE exercicios SET nome = 'Desenvolvimento Ombro (Halteres)' WHERE nome = 'Desenvolvimento Ombro';
UPDATE exercicios SET nome = 'Abdominal Supra (Solo)' WHERE nome = 'Abdominal Supra';

INSERT INTO exercicios (nome, grupo_muscular) VALUES
-- ===== Peito =====
('Supino Reto (Halteres)', 'Peito'),
('Supino Reto (Máquina)', 'Peito'),
('Supino Reto (Smith)', 'Peito'),
('Supino Inclinado (Barra)', 'Peito'),
('Supino Inclinado (Halteres)', 'Peito'),
('Supino Inclinado (Máquina)', 'Peito'),
('Supino Inclinado (Smith)', 'Peito'),
('Supino Declinado (Barra)', 'Peito'),
('Supino Declinado (Halteres)', 'Peito'),
('Crucifixo Inclinado (Halteres)', 'Peito'),
('Crucifixo Declinado (Halteres)', 'Peito'),
('Crucifixo (Polia Baixa)', 'Peito'),
('Crucifixo (Polia Alta)', 'Peito'),
('Peck Deck (Voador)', 'Peito'),
('Cross Over (Polia Alta)', 'Peito'),
('Cross Over (Polia Baixa)', 'Peito'),
('Flexão de Braço', 'Peito'),
('Flexão de Braço Diamante', 'Peito'),
('Flexão de Braço Inclinada', 'Peito'),
('Flexão de Braço Declinada', 'Peito'),
('Paralelas (Peito)', 'Peito'),
('Pullover com Halteres', 'Peito'),
('Pullover na Polia', 'Peito'),
('Supino Fechado (Barra)', 'Peito'),
('Supino Guilhotina (Barra)', 'Peito'),
('Flexão com Palmas', 'Peito'),
('Crucifixo na Máquina Unilateral', 'Peito'),

-- ===== Costas =====
('Puxada Frontal (Pegada Fechada)', 'Costas'),
('Puxada Frontal (Pegada Supinada)', 'Costas'),
('Puxada Atrás da Nuca', 'Costas'),
('Barra Fixa (Pull-up)', 'Costas'),
('Barra Fixa (Chin-up)', 'Costas'),
('Barra Fixa Assistida (Máquina)', 'Costas'),
('Remada Curvada (Halteres)', 'Costas'),
('Remada Unilateral (Halteres)', 'Costas'),
('Remada Cavalinho (T-Bar)', 'Costas'),
('Remada Baixa (Cabo, Pegada Fechada)', 'Costas'),
('Remada Baixa (Cabo, Pegada Aberta)', 'Costas'),
('Remada Máquina Articulada', 'Costas'),
('Remada Alta (Barra)', 'Costas'),
('Remada Serrote', 'Costas'),
('Remada Invertida (Peso Corporal)', 'Costas'),
('Levantamento Terra (Barra)', 'Costas'),
('Levantamento Terra Romeno (Barra)', 'Costas'),
('Levantamento Terra Romeno (Halteres)', 'Costas'),
('Levantamento Terra Sumô', 'Costas'),
('Levantamento Terra com Trap Bar', 'Costas'),
('Pulldown Braço Reto (Polia)', 'Costas'),
('Face Pull (Polia)', 'Costas'),
('Remada Cavalo (Landmine)', 'Costas'),
('Puxada Neutra (Triângulo)', 'Costas'),
('Puxada Unilateral (Polia)', 'Costas'),
('Remada com Kettlebell', 'Costas'),

-- ===== Ombro =====
('Desenvolvimento Militar (Barra)', 'Ombro'),
('Desenvolvimento Máquina', 'Ombro'),
('Desenvolvimento Smith', 'Ombro'),
('Desenvolvimento Arnold', 'Ombro'),
('Desenvolvimento Sentado (Halteres)', 'Ombro'),
('Desenvolvimento em Pé (Halteres)', 'Ombro'),
('Desenvolvimento com Kettlebell', 'Ombro'),
('Elevação Lateral (Halteres)', 'Ombro'),
('Elevação Lateral (Polia)', 'Ombro'),
('Elevação Lateral (Máquina)', 'Ombro'),
('Elevação Lateral Inclinada (Halteres)', 'Ombro'),
('Elevação Lateral na Máquina Unilateral', 'Ombro'),
('Elevação Frontal (Halteres)', 'Ombro'),
('Elevação Frontal (Barra)', 'Ombro'),
('Elevação Frontal (Polia)', 'Ombro'),
('Elevação em W (Halteres)', 'Ombro'),
('Crucifixo Invertido (Halteres)', 'Ombro'),
('Crucifixo Invertido (Máquina/Peck Deck)', 'Ombro'),
('Crucifixo Invertido (Polia)', 'Ombro'),
('Deltoide Posterior (Máquina)', 'Ombro'),
('Remada Alta (Halteres)', 'Ombro'),
('Face Pull para Deltoide Posterior', 'Ombro'),
('Manguito Rotador (Externo, Polia)', 'Ombro'),
('Manguito Rotador (Interno, Polia)', 'Ombro'),
('Rotação Externa com Elástico', 'Ombro'),
('Push Press (Barra)', 'Ombro'),
('Cuban Press (Halteres)', 'Ombro'),

-- ===== Bíceps =====
('Rosca Direta (Halteres)', 'Bíceps'),
('Rosca Alternada (Halteres)', 'Bíceps'),
('Rosca Scott (Barra)', 'Bíceps'),
('Rosca Scott (Halteres)', 'Bíceps'),
('Rosca Scott (Máquina)', 'Bíceps'),
('Rosca Concentrada (Halteres)', 'Bíceps'),
('Rosca Martelo (Halteres)', 'Bíceps'),
('Rosca Martelo (Cabo/Corda)', 'Bíceps'),
('Rosca 21', 'Bíceps'),
('Rosca na Polia (Barra)', 'Bíceps'),
('Rosca na Polia (Corda)', 'Bíceps'),
('Rosca Inversa (Barra)', 'Bíceps'),
('Rosca Spider (Halteres)', 'Bíceps'),
('Rosca Spider (Barra)', 'Bíceps'),
('Rosca Bayesian (Polia)', 'Bíceps'),
('Rosca no Banco Inclinado (Halteres)', 'Bíceps'),
('Rosca Bíceps (Máquina)', 'Bíceps'),
('Rosca Zottman', 'Bíceps'),
('Rosca no TRX', 'Bíceps'),
('Rosca Drag Curl (Barra)', 'Bíceps'),

-- ===== Tríceps =====
('Tríceps Barra (Polia)', 'Tríceps'),
('Tríceps Testa (Barra)', 'Tríceps'),
('Tríceps Testa (Halteres)', 'Tríceps'),
('Tríceps Francês (Halteres)', 'Tríceps'),
('Tríceps Francês (Barra)', 'Tríceps'),
('Tríceps Coice (Halteres)', 'Tríceps'),
('Tríceps Coice (Polia)', 'Tríceps'),
('Mergulho no Banco (Bench Dips)', 'Tríceps'),
('Paralelas (Tríceps)', 'Tríceps'),
('Supino Fechado (Tríceps)', 'Tríceps'),
('Extensão de Tríceps Unilateral (Polia)', 'Tríceps'),
('Extensão de Tríceps Acima da Cabeça (Polia)', 'Tríceps'),
('Extensão de Tríceps na Máquina', 'Tríceps'),
('Kickback (Halteres)', 'Tríceps'),
('Kickback com Elástico', 'Tríceps'),
('Tríceps Barra V (Polia)', 'Tríceps'),
('Tríceps Corda Overhead (Polia)', 'Tríceps'),
('Flexão Diamante (Peso Corporal)', 'Tríceps'),
('Press JM (Barra)', 'Tríceps'),
('Tríceps no Banco com Halteres Atrás da Cabeça', 'Tríceps'),

-- ===== Antebraço =====
('Rosca de Punho (Barra)', 'Antebraço'),
('Rosca de Punho Inversa (Barra)', 'Antebraço'),
('Rosca de Punho (Halteres)', 'Antebraço'),
('Extensão de Punho (Halteres)', 'Antebraço'),
('Flexão de Punho (Halteres)', 'Antebraço'),
('Rosca Antebraço na Polia', 'Antebraço'),
('Farmer''s Walk (Halteres)', 'Antebraço'),
('Farmer''s Walk (Trap Bar)', 'Antebraço'),
('Rosca Reversa (Barra)', 'Antebraço'),
('Suspensão na Barra (Dead Hang)', 'Antebraço'),
('Pinça com Disco (Plate Pinch)', 'Antebraço'),

-- ===== Trapézio =====
('Encolhimento de Ombros (Barra)', 'Trapézio'),
('Encolhimento de Ombros (Halteres)', 'Trapézio'),
('Encolhimento de Ombros (Smith)', 'Trapézio'),
('Encolhimento na Polia', 'Trapézio'),
('Encolhimento na Máquina', 'Trapézio'),
('Remada Alta para Trapézio (Barra)', 'Trapézio'),
('Face Pull para Trapézio', 'Trapézio'),
('Levantamento Terra para Trapézio (Barra)', 'Trapézio'),
('Encolhimento Atrás das Costas (Barra)', 'Trapézio'),
('Encolhimento com Trap Bar', 'Trapézio'),

-- ===== Quadríceps =====
('Agachamento Smith', 'Quadríceps'),
('Agachamento Hack (Máquina)', 'Quadríceps'),
('Agachamento Frontal (Barra)', 'Quadríceps'),
('Agachamento Búlgaro (Halteres)', 'Quadríceps'),
('Agachamento Sumô (Halteres)', 'Quadríceps'),
('Agachamento Goblet (Halteres)', 'Quadríceps'),
('Agachamento Zercher', 'Quadríceps'),
('Agachamento com Kettlebell', 'Quadríceps'),
('Agachamento com Salto (Peso Corporal)', 'Quadríceps'),
('Agachamento com Salto no Box', 'Quadríceps'),
('Agachamento Isométrico na Parede (Wall Sit)', 'Quadríceps'),
('Agachamento Sissy', 'Quadríceps'),
('Agachamento Pistol (Unilateral)', 'Quadríceps'),
('Agachamento no Smith Frontal', 'Quadríceps'),
('Belt Squat', 'Quadríceps'),
('Hack Machine Reverso', 'Quadríceps'),
('Cadeira Extensora', 'Quadríceps'),
('Cadeira Extensora Unilateral', 'Quadríceps'),
('Cadeira Extensora Isométrica', 'Quadríceps'),
('Afundo (Halteres)', 'Quadríceps'),
('Afundo Caminhando (Halteres)', 'Quadríceps'),
('Passada (Barra)', 'Quadríceps'),
('Leg Press Horizontal', 'Quadríceps'),
('Leg Press Unilateral', 'Quadríceps'),
('Leg Press 45° Pés Altos', 'Quadríceps'),
('Agachamento na Máquina Smith Unilateral', 'Quadríceps'),
('Step Up (Halteres)', 'Quadríceps'),
('Step Up (Peso Corporal)', 'Quadríceps'),

-- ===== Posterior de Coxa =====
('Mesa Flexora', 'Posterior de Coxa'),
('Cadeira Flexora', 'Posterior de Coxa'),
('Cadeira Flexora Sentado', 'Posterior de Coxa'),
('Mesa Flexora Unilateral', 'Posterior de Coxa'),
('Flexora Deitado Unilateral', 'Posterior de Coxa'),
('Flexora em Pé (Máquina)', 'Posterior de Coxa'),
('Flexora em Pé (Polia)', 'Posterior de Coxa'),
('Stiff (Barra)', 'Posterior de Coxa'),
('Stiff (Halteres)', 'Posterior de Coxa'),
('Stiff no Smith', 'Posterior de Coxa'),
('Stiff com Kettlebell', 'Posterior de Coxa'),
('Levantamento Terra Romeno (Unilateral)', 'Posterior de Coxa'),
('Terra Romeno com Halteres Unilateral', 'Posterior de Coxa'),
('Good Morning para Posterior', 'Posterior de Coxa'),
('Glute Ham Raise (GHR)', 'Posterior de Coxa'),
('Nordic Curl', 'Posterior de Coxa'),
('Ponte Isométrica Unilateral', 'Posterior de Coxa'),

-- ===== Glúteos =====
('Elevação Pélvica (Hip Thrust, Barra)', 'Glúteos'),
('Elevação Pélvica (Máquina)', 'Glúteos'),
('Elevação Pélvica Unilateral', 'Glúteos'),
('Elevação Pélvica com Barra e Pausa', 'Glúteos'),
('Elevação Pélvica com Banda Elástica', 'Glúteos'),
('Ponte de Glúteo (Solo)', 'Glúteos'),
('Ponte de Glúteo (Halteres)', 'Glúteos'),
('Abdução de Quadril (Máquina)', 'Glúteos'),
('Abdução de Quadril (Polia)', 'Glúteos'),
('Abdução em Pé na Polia', 'Glúteos'),
('Cadeira Abdutora', 'Glúteos'),
('Cadeira Adutora (Adutores)', 'Glúteos'),
('Adução de Quadril na Polia', 'Glúteos'),
('Coice de Glúteo (Cabo/Polia)', 'Glúteos'),
('Coice de Glúteo (Máquina)', 'Glúteos'),
('Glúteo 4 Apoios (Coice no Solo)', 'Glúteos'),
('Passo Lateral com Elástico (Banda)', 'Glúteos'),
('Frog Pump', 'Glúteos'),
('Step Up com Foco em Glúteo', 'Glúteos'),

-- ===== Panturrilha =====
('Panturrilha em Pé (Máquina)', 'Panturrilha'),
('Panturrilha Sentado (Máquina)', 'Panturrilha'),
('Panturrilha no Leg Press', 'Panturrilha'),
('Panturrilha no Smith', 'Panturrilha'),
('Panturrilha Unilateral (Halteres)', 'Panturrilha'),
('Panturrilha no Step (Peso Corporal)', 'Panturrilha'),
('Panturrilha na Barra Guiada', 'Panturrilha'),
('Panturrilha Burrinho (Donkey Calf Raise)', 'Panturrilha'),
('Panturrilha na Prensa Horizontal', 'Panturrilha'),
('Panturrilha com Salto (Peso Corporal)', 'Panturrilha'),
('Panturrilha Isométrica na Parede', 'Panturrilha'),

-- ===== Abdômen =====
('Abdominal Infra (Elevação de Pernas)', 'Abdômen'),
('Abdominal Infra na Barra (Elevação de Joelhos)', 'Abdômen'),
('Abdominal Infra na Barra (Elevação de Pernas)', 'Abdômen'),
('Abdominal Infra no Solo', 'Abdômen'),
('Abdominal Oblíquo (Solo)', 'Abdômen'),
('Abdominal na Máquina', 'Abdômen'),
('Abdominal na Polia Alta (Crunch)', 'Abdômen'),
('Abdominal Bicicleta', 'Abdômen'),
('Abdominal Canivete (V-Up)', 'Abdômen'),
('Abdominal Remador', 'Abdômen'),
('Abdominal Declinado (Banco)', 'Abdômen'),
('Abdominal Máquina Rotação', 'Abdômen'),
('Abdominal Crunch na Bola Suíça', 'Abdômen'),
('Abdominal na Bola Suíça com Rotação', 'Abdômen'),
('Sit-up Completo', 'Abdômen'),
('Prancha Abdominal (Frontal)', 'Abdômen'),
('Prancha Lateral', 'Abdômen'),
('Prancha com Elevação de Perna', 'Abdômen'),
('Prancha com Toque no Ombro', 'Abdômen'),
('Prancha Dinâmica (Spiderman)', 'Abdômen'),
('Rotação de Tronco na Polia (Woodchopper)', 'Abdômen'),
('Rotação de Tronco com Halteres (Russian Twist)', 'Abdômen'),
('Elevação de Pernas na Cadeira Romana', 'Abdômen'),
('Roda Abdominal (Ab Wheel)', 'Abdômen'),
('Dead Bug', 'Abdômen'),
('Hollow Hold', 'Abdômen'),
('Mountain Climber', 'Abdômen'),
('Toes to Bar', 'Abdômen'),
('Flutter Kicks', 'Abdômen'),

-- ===== Lombar =====
('Hiperextensão Lombar (Banco Romano)', 'Lombar'),
('Hiperextensão Lombar com Peso', 'Lombar'),
('Good Morning', 'Lombar'),
('Superman (Solo)', 'Lombar'),
('Levantamento Terra para Lombar', 'Lombar'),
('Extensão Lombar na Máquina', 'Lombar'),
('Ponte Lombar (Bird Dog)', 'Lombar'),
('Reverse Hyperextension', 'Lombar'),
('Stiff para Lombar', 'Lombar'),
('Prancha com Extensão Lombar', 'Lombar'),

-- ===== Funcional =====
('Kettlebell Swing', 'Funcional'),
('Battle Rope (Ondulação)', 'Funcional'),
('Box Jump', 'Funcional'),
('Burpee', 'Funcional'),
('Sled Push (Trenó Empurrar)', 'Funcional'),
('Sled Pull (Trenó Puxar)', 'Funcional'),
('Sled Drag Lateral', 'Funcional'),
('TRX Remada', 'Funcional'),
('TRX Supino', 'Funcional'),
('TRX Agachamento', 'Funcional'),
('Mountain Climber com TRX', 'Funcional'),
('Corda Naval (Battle Rope Alternado)', 'Funcional'),
('Arremesso de Medicine Ball (Slam Ball)', 'Funcional'),
('Wall Ball', 'Funcional'),
('Turkish Get-Up', 'Funcional'),
('Clean (Levantamento Olímpico)', 'Funcional'),
('Clean and Press', 'Funcional'),
('Snatch (Arranco)', 'Funcional'),
('Thruster (Barra)', 'Funcional'),
('Farmer''s Carry', 'Funcional'),
('Tire Flip (Virada de Pneu)', 'Funcional'),
('Push Press com Halteres', 'Funcional'),
('Bear Crawl', 'Funcional'),
('Battle Rope com Agachamento', 'Funcional'),
('Carregada de Sandbag (Sandbag Carry)', 'Funcional'),

-- ===== Complementares (variações adicionais) =====
('Supino Máquina Convergente', 'Peito'),
('Flexão com Elevação de Pernas (Peito Superior)', 'Peito'),
('Remada Explosiva (Barra)', 'Costas'),
('Pulldown Unilateral (Corda)', 'Costas'),
('Arnold Press Sentado', 'Ombro'),
('Elevação Lateral Deitado de Lado (Halteres)', 'Ombro'),
('Rosca Preacher Unilateral (Halteres)', 'Bíceps'),
('Rosca com Barra EZ', 'Bíceps'),
('Tríceps Testa no Smith', 'Tríceps'),
('Extensão de Tríceps com Halteres Unilateral', 'Tríceps'),
('Rolo de Punho (Wrist Roller)', 'Antebraço'),
('Prancha com Rotação de Punho', 'Antebraço'),
('Encolhimento Unilateral (Halteres)', 'Trapézio'),
('Remada Alta Estreita (Polia)', 'Trapézio'),
('Agachamento Livre (Halteres)', 'Quadríceps'),
('Leg Press Vertical', 'Quadríceps'),
('Flexora Unilateral na Polia', 'Posterior de Coxa'),
('Stiff Unilateral (Halteres)', 'Posterior de Coxa'),
('Elevação Pélvica no Smith', 'Glúteos'),
('Cadeira Abdutora Isométrica', 'Glúteos'),
('Panturrilha Sentado com Barra', 'Panturrilha'),
('Panturrilha Unilateral no Step', 'Panturrilha'),
('Prancha com Apoio Instável (Bosu)', 'Abdômen'),
('Abdominal Infra Suspenso (Argolas)', 'Abdômen'),
('Hiperextensão Unilateral', 'Lombar'),
('Good Morning no Smith', 'Lombar')

ON CONFLICT (nome) DO NOTHING;
